### ISSUE TITLE
iOS release

### ISSUE THREAD

**Issue by Seexelas** [tatsutron/mistercon#3]
Hi,

Any chance that we can get this application on iOS too please ?

Thanks

Take care

Best regards

**Comment by tatsutron** [comment]
You're in luck! It's early days yet but I've just announced an iOS port over [here](https://www.youtube.com/watch?v=2VYFRSbXMlk). Thanks for the question.

**Comment by leolobato** [comment]
@tatsutron Good news about the iOS app, but that link is dead. Is there a public repo where I could contribute?

**Comment by tatsutron** [comment]
@leolobato thanks for asking! There is nothing public as of yet, but eventually it'll be a part of this repo

**Comment by Seexelas** [comment]
Hi :) 

Maybe a possibility to do a TestFlight access ? 

Thanks
