### ISSUE TITLE
Feature request: Favorites/Bookmarks

### ISSUE THREAD

**Issue by Kopert** [tatsutron/mistercon#4]
**_Feature request_**: Favorites/Bookmarks.

**_Feature description_**: Have a menu called "Favorites", "Bookmarks" or something similar. On this menu, allow the creation of Categories/Subcategories (like a folder tree found on most browser bookmark systems) where we can add roms and arcade games to launch directly.

**_Additional functionality_**: ideally one should be able to add roms/arcade games to the list while navigating the list, edit the names of the categories/subcategories/roms on the list and add games to favorites while navigating other parts of the system (any interface that works as a rom navigation screen, for example).

On another note, people can use this system for any other functionality other than just favorites, like having a "play later" list or organizing their games by category or something to that effect. With this in mind, I believe a generic "Bookmarks" system would be more powerful than a specialized "Favorites" system, if that makes sense.

**Comment by tatsutron** [comment]
[1.1.0](https://github.com/tatsutron/mistercon/releases/tag/v1.1.0) adds a favorites feature, though it works differently from what is described here.
