### ISSUE TITLE
Feature request: Support for Arcade games

### ISSUE THREAD

**Issue by Kopert** [tatsutron/mistercon#5]
**_Feature request_**: Support for Arcade games.

**_Feature description_**: The application currently supports launching roms for cores. It should also be able to support launching arcade cores.

**_Additional functionality_**: in the future it might be interesting to be able to browse arcade games by year, genre, developer etc.

**Comment by tatsutron** [comment]
Thanks for the suggestion! This feature is now part of the roadmap. Just in case you're interested we're currently soliciting feedback on which features to prioritize (the idea is to vote for your top three). There's a video going over the full list of candidates [here](https://youtu.be/2VYFRSbXMlk).

**Comment by tatsutron** [comment]
Arcade support (for `*.mra`) is in as of v.1.3.0!
