### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by retrorepair** [tatsutron/mistercon#8]
It looks like a lot of cool stuff has been added since the last release, how do you compile? Is another release in the works soon?

**Comment by tatsutron** [comment]
Hello and thanks for the question! Builds with features that are still in beta are Patron-only. That said, there will be another public release coming up before long too.

**Comment by tatsutron** [comment]
Update on this: we are now full steam ahead on the new public release of mistercon which will include all beta features developed to this point, as well as some small new additions. We'll leave this issue open until the release is completed.

**Comment by tatsutron** [comment]
Hey @retrorepair wanted to give a heads up that we've just published a new release (with an attached APK). Fyi this new release requires [mister-server](https://github.com/tatsutron/mister-server) so you'll want to install that first.

**Comment by retrorepair** [comment]
I'll take a look at some point, thanks. I do think this is pretty high level for most people though which is a shame since this has a ton of potential

**Comment by retrorepair** [comment]
Maybe a bit high level for me too. How does one scp from windows to linux (I'm using KiTTY). I ftp'd it over and arcade games are found and the mister menu can be called, but it always returns an ip error for consoles and scripts.

**Comment by tatsutron** [comment]
Hey! Wow this is super late, but we're finally back after a long disaster that prevented us from working on this project. We're back now though, and we've taken your suggestions to heart. In other words, we dropped the `mister-server` requirement. Now, all that is required is downloading the APK and installing it on your android device. You can get the latest version of the app here: https://github.com/tatsutron/mistercon/releases/tag/v1.4.0
