### ISSUE TITLE
Support for Game ROMs stored in Zip Files

### ISSUE THREAD

**Issue by ddcruver** [tatsutron/mistercon#9]
The MiSTer system supports ROMS being located in Zip files and treats each Zip file as a folder.  It would be nice if this app could do that as well.

**Comment by tatsutron** [comment]
You are a mind reader! That's literally the next feature we've got in the works :D I'll follow up here once a new release with it is ready

**Comment by tatsutron** [comment]
Support for this is now included in the latest releases. It is not yet enabled for all platforms, so please check the readme to see which platforms are supported thus far.
